# Generated by Django 5.0.4 on 2024-04-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_users_alter_upload_action'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='Student',
        ),
    ]
