# Generated by Django 5.0.4 on 2024-04-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_rename_users_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterField(
            model_name='upload',
            name='action',
            field=models.CharField(max_length=50),
        ),
    ]
