# Generated by Django 5.0.4 on 2024-04-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_upload_height_upload_width_alter_upload_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadVid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/%y')),
                ('action', models.CharField(max_length=50)),
                ('width', models.IntegerField(default=500)),
                ('height', models.IntegerField(default=500)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
